### PR TITLE
Custom rendering

### PR DESCRIPTION
**Pull request by marcolink**
# Description
Introduce custom rendering of content types.  

A [`ContentTypeRenderer`](https://github.com/contentful-userland/cf-content-types-generator/blob/feat/render-config/src/type-renderer/content-type-renderer.ts) class to be extended for custom rendering purposes. Different render cycle methods can be overridden to achieve custom results.

Relevant methods to override:

| Methods             | Description                                                  | Override                                                     |
| ------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| `render`            | Enriches a `SourceFile` with all relevant nodes              | To control content type rendering (you should know what you're doing) |
| `getContext`        | Returns new render context object                            | To define custom type renderer and custom module name function |
| `addDefaultImports` | Define set of default imports added to every file            | To control default imported modules                          |
| `renderField`       | Returns a `PropertySignatureStructure` representing a field property | To control Field property rendering                          |
| `renderFieldType`   | Returns a `string` representing a field type                 | To control field type rendering (recommended)                |
| `renderEntry`       | Returns a `TypeAliasDeclarationStructure` representing an entry type alias | To control entry type alias rendering                        |
| `renderEntryType`   | Returns a `string` representing an entry type                | To control entry type rendering (recommended)                |

> Table represents the order of execution

A set of [tests](https://github.com/contentful-userland/cf-content-types-generator/blob/feat/render-config/test/content-type-renfderer.test.ts) showcase simple use cases.

Possibly solves #109

### CODE REVIEW

**Comment by cysp** [comment]
This looks great, is there anything I can do to help get this new custom rendering functionality landed? 🙂

**Comment by marcolink** [comment]
Hi @cysp,

I don't see any blockers right now- was just hoping for some reviews on this ;)

**Comment by cysp** [comment]
I've only had about a week's familiarity with this project, and only using it in CLI form, but the code change here looks reasonable to me, the custom rendering interface allows me to provide the customisation I'm currently looking for and it all seems to work.
So for whatever that's worth, 👍 from me 😆

**Comment by marcolink** [comment]
@cysp I'll have time next week to finish this up.

**Pull request merged**
